=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::AddressesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AddressesApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::AddressesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressesApi' do
    it 'should create an instance of AddressesApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::AddressesApi)
    end
  end

  # unit tests for get_checkout_address
  # Get checkout address
  # Retrieves a checkout&#39;s address.
  # @param checkout_id The order number
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Address]
  describe 'get_checkout_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_order_address
  # Get order address
  # Retrieves an order&#39;s address.
  # @param order_number The order number
  # @param id The id of the order&#39;s address that we want to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Address]
  describe 'get_order_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_checkout_address
  # Update checkout address
  # Updates a checkout&#39;s address.
  # @param checkout_id The order number
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateCheckoutAddressRequest] :update_checkout_address_request 
  # @return [Address]
  describe 'update_checkout_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_order_address
  # Update order address
  # Updates an order&#39;s address.
  # @param order_number The order number
  # @param id The id of the order&#39;s address that we want to retrieve
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateCheckoutAddressRequest] :update_checkout_address_request 
  # @return [Address]
  describe 'update_order_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
