=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::CheckoutsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckoutsApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::CheckoutsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutsApi' do
    it 'should create an instance of CheckoutsApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::CheckoutsApi)
    end
  end

  # unit tests for advance_checkout
  # Advance checkout
  # Advances a checkout to the furthest possible state.
  # @param checkout_id The order number
  # @param [Hash] opts the optional parameters
  # @return [OrderBig]
  describe 'advance_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for complete_checkout
  # Complete checkout
  # Completes a checkout.
  # @param checkout_id The order number
  # @param [Hash] opts the optional parameters
  # @option opts [CompleteCheckoutRequest] :complete_checkout_request 
  # @return [OrderBig]
  describe 'complete_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transition_checkout
  # Transition checkout
  # Transitions a checkout to the next state.
  # @param checkout_id The order number
  # @param [Hash] opts the optional parameters
  # @option opts [CompleteCheckoutRequest] :complete_checkout_request 
  # @return [OrderBig]
  describe 'transition_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_checkout
  # Update checkout
  # Updates a checkout and moves the order to the next checkout step. A request with an empty body is legit and only tries to move the order to the next step.  To perform this operation the request should be made as the order owner or with the order token in case of unauthenitcated checkouts (es. guest checkout).  **Note:** In addition to the order update, this action always attempts to perform an order state machine transition which results in a &#x60;422&#x60; response if it cannot be transitioned.
  # @param id The order number
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateOrderRequest] :update_order_request 
  # @return [OrderBig]
  describe 'update_checkout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
