=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::ClassificationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClassificationsApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::ClassificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClassificationsApi' do
    it 'should create an instance of ClassificationsApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::ClassificationsApi)
    end
  end

  # unit tests for update_classification
  # Update classification
  # Updates a classification.  This method only updates the classification position.
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateClassificationRequest] :update_classification_request 
  # @return [Object]
  describe 'update_classification test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
