=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::CouponCodesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CouponCodesApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::CouponCodesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CouponCodesApi' do
    it 'should create an instance of CouponCodesApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::CouponCodesApi)
    end
  end

  # unit tests for create_order_coupon_code
  # Create order coupon code
  # Creates a coupon code for an order.  To perform this operation the request should be made as the order&#39;s owner or with the order token in case of unauthenitcated checkouts (es. guest checkout).
  # @param order_number The order number
  # @param [Hash] opts the optional parameters
  # @option opts [CouponCodeInput] :coupon_code_input 
  # @return [CouponCodeHandler]
  describe 'create_order_coupon_code test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_order_coupon_code
  # Delete order coupon code
  # Deletes an order&#39;s coupon code.  To perform this operation the request should be made as the order&#39;s owner or with the order token in case of unauthenitcated checkouts (es. guest checkout).
  # @param order_number The order number
  # @param id This is the coupon code
  # @param [Hash] opts the optional parameters
  # @return [CouponCodeHandler]
  describe 'delete_order_coupon_code test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
