=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::OptionTypesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OptionTypesApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::OptionTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OptionTypesApi' do
    it 'should create an instance of OptionTypesApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::OptionTypesApi)
    end
  end

  # unit tests for create_option_type
  # Create option type
  # Creates an option type.
  # @param [Hash] opts the optional parameters
  # @option opts [OptionTypeInput] :option_type_input 
  # @return [OptionType]
  describe 'create_option_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_option_type
  # Delete option type
  # Deletes an option type.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [OptionType]
  describe 'delete_option_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_option_type
  # Get option type
  # Retrieve an option type.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [OptionType]
  describe 'get_option_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_option_types
  # List option types
  # Lists the system&#39;s option types.
  # @param [Hash] opts the optional parameters
  # @return [Array<OptionType>]
  describe 'list_option_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_option_type
  # Update option type
  # Updates an option type.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [OptionType] :option_type 
  # @return [OptionType]
  describe 'update_option_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
