=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::StockMovementsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StockMovementsApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::StockMovementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StockMovementsApi' do
    it 'should create an instance of StockMovementsApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::StockMovementsApi)
    end
  end

  # unit tests for create_stock_location_movement
  # Create stock location movement
  # Creates a stock movement for a stock location.
  # @param stock_location_id 
  # @param [Hash] opts the optional parameters
  # @option opts [StockMovementInput] :stock_movement_input 
  # @return [StockMovement]
  describe 'create_stock_location_movement test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_stock_location_movement
  # Get stock location movement
  # Retrieves a stock location&#39;s movement.
  # @param stock_location_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_stock_location_movement test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_stock_location_movements
  # List stock location movements
  # Lists a stock location&#39;s movements.
  # @param stock_location_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [Object] :q Allows to query results based on search filters provided by Ransack (https://github.com/activerecord-hackery/ransack/).
  # @return [ListStockLocationMovements200Response]
  describe 'list_stock_location_movements test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
