=begin
#solidus_subscriptions

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::SubscriptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubscriptionsApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::SubscriptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionsApi' do
    it 'should create an instance of SubscriptionsApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::SubscriptionsApi)
    end
  end

  # unit tests for patch_subscriptions_api_v1_subscriptions_id
  # Update Subscription
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchSubscriptionsApiV1SubscriptionsIdRequest] :patch_subscriptions_api_v1_subscriptions_id_request 
  # @return [PatchSubscriptionsApiV1SubscriptionsId200Response]
  describe 'patch_subscriptions_api_v1_subscriptions_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_subscriptions_api_v1_subscriptions_id_activate
  # Activate Subscription
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionOutput]
  describe 'post_subscriptions_api_v1_subscriptions_id_activate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_subscriptions_api_v1_subscriptions_id_cancel
  # Cancel Subscription
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionOutput]
  describe 'post_subscriptions_api_v1_subscriptions_id_cancel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_subscriptions_api_v1_subscriptions_id_skip
  # Skip Subscription
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionOutput]
  describe 'post_subscriptions_api_v1_subscriptions_id_skip test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
