=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::TaxonomiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxonomiesApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::TaxonomiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxonomiesApi' do
    it 'should create an instance of TaxonomiesApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::TaxonomiesApi)
    end
  end

  # unit tests for create_taxonomy
  # Create taxonomy
  # Creates a taxonomy.  Only users with the &#x60;create&#x60; permission on &#x60;Spree::Taxonomy&#x60; can perform this action.  Creating a taxonomy, its root taxon with the same name will be automatically created. The root taxon&#39;s information will be available in the response.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTaxonomyRequest] :create_taxonomy_request 
  # @return [Taxonomy]
  describe 'create_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_taxonomy
  # Delete taxonomy
  # Deletes a taxonomy.
  # @param id The id of the taxonomy
  # @param [Hash] opts the optional parameters
  # @return [Taxonomy]
  describe 'delete_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_taxonomy
  # Get taxonomy
  # Retrieves a taxonomy.
  # @param id The id of the taxonomy
  # @param [Hash] opts the optional parameters
  # @option opts [String] :set When &#x60;set&#x3D;nested&#x60; it will recoursively return all the taxons of that taxonomy
  # @return [Object]
  describe 'get_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_taxonomies
  # List taxonomies
  # Lists the taxonomies.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [Object] :q Allows to query results based on search filters provided by Ransack (https://github.com/activerecord-hackery/ransack/).
  # @return [ListTaxonomies200Response]
  describe 'list_taxonomies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_taxonomy
  # Update taxonomy
  # Updates a taxonomy.  Only users with the &#x60;update&#x60; permission on the taxonomy can perform this action.
  # @param id The id of the taxonomy
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTaxonomyRequest] :create_taxonomy_request 
  # @return [Taxonomy]
  describe 'update_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
