=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SolidusSdk::ZonesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ZonesApi' do
  before do
    # run before each test
    @api_instance = SolidusSdk::ZonesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ZonesApi' do
    it 'should create an instance of ZonesApi' do
      expect(@api_instance).to be_instance_of(SolidusSdk::ZonesApi)
    end
  end

  # unit tests for create_zone
  # Create zone
  # Creates a zone.  Only users with the &#x60;create&#x60; permission on &#x60;Spree::Zone&#x60; can perform this action.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateZoneRequest] :create_zone_request 
  # @return [Zone]
  describe 'create_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_zone
  # Delete zone
  # Deletes a zone.
  # @param id The ID of the zone we want to update
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'delete_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_zone
  # Get zone
  # Retrieves a zone.
  # @param id The ID of the zone we want to update
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'get_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_zones
  # List zones
  # Lists all zones.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [Object] :q Allows to query results based on search filters provided by Ransack (https://github.com/activerecord-hackery/ransack/).
  # @return [ListZones200Response]
  describe 'list_zones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_zone
  # Update zone
  # Updates a zone.  Only users with the &#x60;update&#x60; permission on the zone can perform this action.
  # @param id The ID of the zone we want to update
  # @param [Hash] opts the optional parameters
  # @option opts [CreateZoneRequest] :create_zone_request 
  # @return [Zone]
  describe 'update_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
