=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SolidusSdk::AddShipmentItemRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SolidusSdk::AddShipmentItemRequest do
  let(:instance) { SolidusSdk::AddShipmentItemRequest.new }

  describe 'test an instance of AddShipmentItemRequest' do
    it 'should create an instance of AddShipmentItemRequest' do
      expect(instance).to be_instance_of(SolidusSdk::AddShipmentItemRequest)
    end
  end
  describe 'test attribute "variant_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "quantity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
