=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SolidusSdk::GetConfig200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SolidusSdk::GetConfig200Response do
  let(:instance) { SolidusSdk::GetConfig200Response.new }

  describe 'test an instance of GetConfig200Response' do
    it 'should create an instance of GetConfig200Response' do
      expect(instance).to be_instance_of(SolidusSdk::GetConfig200Response)
    end
  end
  describe 'test attribute "default_country_iso"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
