=begin
#solidus_subscriptions

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SolidusSdk::PatchSubscriptionsApiV1SubscriptionsIdRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SolidusSdk::PatchSubscriptionsApiV1SubscriptionsIdRequest do
  let(:instance) { SolidusSdk::PatchSubscriptionsApiV1SubscriptionsIdRequest.new }

  describe 'test an instance of PatchSubscriptionsApiV1SubscriptionsIdRequest' do
    it 'should create an instance of PatchSubscriptionsApiV1SubscriptionsIdRequest' do
      expect(instance).to be_instance_of(SolidusSdk::PatchSubscriptionsApiV1SubscriptionsIdRequest)
    end
  end
  describe 'test attribute "subscription"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
