=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SolidusSdk::ReturnAuthorizationInputReturnItemsAttributesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SolidusSdk::ReturnAuthorizationInputReturnItemsAttributesInner do
  let(:instance) { SolidusSdk::ReturnAuthorizationInputReturnItemsAttributesInner.new }

  describe 'test an instance of ReturnAuthorizationInputReturnItemsAttributesInner' do
    it 'should create an instance of ReturnAuthorizationInputReturnItemsAttributesInner' do
      expect(instance).to be_instance_of(SolidusSdk::ReturnAuthorizationInputReturnItemsAttributesInner)
    end
  end
  describe 'test attribute "inventory_unit_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "exchange_variant_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "return_reason_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
