=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SolidusSdk::SelectShipmentShippingMethodRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SolidusSdk::SelectShipmentShippingMethodRequest do
  let(:instance) { SolidusSdk::SelectShipmentShippingMethodRequest.new }

  describe 'test an instance of SelectShipmentShippingMethodRequest' do
    it 'should create an instance of SelectShipmentShippingMethodRequest' do
      expect(instance).to be_instance_of(SolidusSdk::SelectShipmentShippingMethodRequest)
    end
  end
  describe 'test attribute "shipping_method_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
