=begin
#Solidus API

#The standard Solidus API.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0-SNAPSHOT

=end

require 'date'
require 'time'

module SolidusSdk
  class Product
    attr_accessor :available_on

    attr_accessor :classifications

    attr_accessor :description

    attr_accessor :display_price

    attr_accessor :has_variants

    attr_accessor :id

    attr_accessor :master

    attr_accessor :meta_description

    attr_accessor :meta_keywords

    attr_accessor :meta_title

    attr_accessor :name

    attr_accessor :option_types

    attr_accessor :price

    attr_accessor :product_properties

    attr_accessor :shipping_category_id

    attr_accessor :slug

    attr_accessor :taxon_ids

    attr_accessor :total_on_hand

    attr_accessor :variants

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'available_on' => :'available_on',
        :'classifications' => :'classifications',
        :'description' => :'description',
        :'display_price' => :'display_price',
        :'has_variants' => :'has_variants',
        :'id' => :'id',
        :'master' => :'master',
        :'meta_description' => :'meta_description',
        :'meta_keywords' => :'meta_keywords',
        :'meta_title' => :'meta_title',
        :'name' => :'name',
        :'option_types' => :'option_types',
        :'price' => :'price',
        :'product_properties' => :'product_properties',
        :'shipping_category_id' => :'shipping_category_id',
        :'slug' => :'slug',
        :'taxon_ids' => :'taxon_ids',
        :'total_on_hand' => :'total_on_hand',
        :'variants' => :'variants'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'available_on' => :'String',
        :'classifications' => :'Array<Classification>',
        :'description' => :'String',
        :'display_price' => :'String',
        :'has_variants' => :'Boolean',
        :'id' => :'Integer',
        :'master' => :'Variant',
        :'meta_description' => :'String',
        :'meta_keywords' => :'String',
        :'meta_title' => :'String',
        :'name' => :'String',
        :'option_types' => :'Array<OptionType>',
        :'price' => :'String',
        :'product_properties' => :'Array<ProductProperty>',
        :'shipping_category_id' => :'Integer',
        :'slug' => :'String',
        :'taxon_ids' => :'Array<Integer>',
        :'total_on_hand' => :'Integer',
        :'variants' => :'Array<Variant>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SolidusSdk::Product` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SolidusSdk::Product`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'available_on')
        self.available_on = attributes[:'available_on']
      end

      if attributes.key?(:'classifications')
        if (value = attributes[:'classifications']).is_a?(Array)
          self.classifications = value
        end
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'display_price')
        self.display_price = attributes[:'display_price']
      end

      if attributes.key?(:'has_variants')
        self.has_variants = attributes[:'has_variants']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'master')
        self.master = attributes[:'master']
      end

      if attributes.key?(:'meta_description')
        self.meta_description = attributes[:'meta_description']
      end

      if attributes.key?(:'meta_keywords')
        self.meta_keywords = attributes[:'meta_keywords']
      end

      if attributes.key?(:'meta_title')
        self.meta_title = attributes[:'meta_title']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'option_types')
        if (value = attributes[:'option_types']).is_a?(Array)
          self.option_types = value
        end
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      end

      if attributes.key?(:'product_properties')
        if (value = attributes[:'product_properties']).is_a?(Array)
          self.product_properties = value
        end
      end

      if attributes.key?(:'shipping_category_id')
        self.shipping_category_id = attributes[:'shipping_category_id']
      end

      if attributes.key?(:'slug')
        self.slug = attributes[:'slug']
      end

      if attributes.key?(:'taxon_ids')
        if (value = attributes[:'taxon_ids']).is_a?(Array)
          self.taxon_ids = value
        end
      end

      if attributes.key?(:'total_on_hand')
        self.total_on_hand = attributes[:'total_on_hand']
      end

      if attributes.key?(:'variants')
        if (value = attributes[:'variants']).is_a?(Array)
          self.variants = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          available_on == o.available_on &&
          classifications == o.classifications &&
          description == o.description &&
          display_price == o.display_price &&
          has_variants == o.has_variants &&
          id == o.id &&
          master == o.master &&
          meta_description == o.meta_description &&
          meta_keywords == o.meta_keywords &&
          meta_title == o.meta_title &&
          name == o.name &&
          option_types == o.option_types &&
          price == o.price &&
          product_properties == o.product_properties &&
          shipping_category_id == o.shipping_category_id &&
          slug == o.slug &&
          taxon_ids == o.taxon_ids &&
          total_on_hand == o.total_on_hand &&
          variants == o.variants
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [available_on, classifications, description, display_price, has_variants, id, master, meta_description, meta_keywords, meta_title, name, option_types, price, product_properties, shipping_category_id, slug, taxon_ids, total_on_hand, variants].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SolidusSdk.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
